#! /usr/bin/python
# -*- coding: utf-8 -*-

__author__ = 'Raúl Jornet Calomarde'
__contact__ = 'rjornetc@openmailbox.org'
__copyright__ = 'Copyright © 2015, Raúl Jornet Calomarde'
__license__ = ''''License GPLv3+: GNU GPL version 3 or any later
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or any later version. This program
is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.
<http://www.gnu.org/licenses/>'''
__date__ = '08/02/2015'
__version__ = '0.1.0'


from math import cos, sin, pi

class RadialGraphSerie():
    title = ''
    color = ''
    values = []
    
    def __init__(self, title, color='#ff0000'):
        self.title = title
        self.color = color
    
    def set_values(self, values):
        self.values = values

class RadialGraph():
    
    title = ''
    axis_title = []
    axis_color = '#777777'
    axis_color_secundary = '#cccccc'
    series = []
    min_value = 0
    max_value = 10
    radial_lines = 10
    radial_axis_primary = 2
    
    def __init__(self, title, axis_title):
        self.title = title
        self.axis_title = axis_title
    
    
    def add_serie(self, serie):
        if len(serie.values) == len(self.axis_title):
            self.series.append(serie)
        else:
            print(':(') #TODO Raise
    
    
    def add_value(self, serie, axis_title, value):
        axis_index = self.axis_title.index(axis_title)
        self.series[serie][axis_index] = value
    
    
    def get_svg(self):
        svg = '''<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:cc="http://creativecommons.org/ns#"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:svg="http://www.w3.org/2000/svg"
  xmlns="http://www.w3.org/2000/svg"
  width="256"
  height="256"
>
  <g transform="translate(128,128)" id="background">'''
        axis_title_count = len(self.axis_title)
        axis_title_angle = 2 * pi / axis_title_count
        radial_lines_space = 96.0 / self.radial_lines
        for i in range(1, self.radial_lines+1):
            svg += '''
    <path d="M '''
            if i % self.radial_axis_primary == 0:
                current_color = self.axis_color
            else:
                current_color = self.axis_color_secundary
            
            for j in range(0, axis_title_count):
                current_angle = axis_title_angle * (j)
                svg += str(sin(current_angle) * radial_lines_space * i) + ',' +\
                       str(-cos(current_angle) * radial_lines_space * i) + ' '
            svg += '''z" id="radial-line''' + str(i) + '''" style="fill:none;stroke:''' + current_color + '''" />'''
        
        for i in range(0, axis_title_count):
            current_angle = axis_title_angle * i
            svg += '''
    <path d="M 0,0 ''' +\
        str(sin(current_angle) * 96) + ',' +\
        str(-cos(current_angle) * 96) + '" id="' +\
        self.axis_title[i] + '''-axis" style="stroke:#777777" />
    <text
      style="font-size:16px;text-align:center;fill:#000000"
      id="''' + self.axis_title[i] + '''-text"
    >
      <tspan
        id="''' + self.axis_title[i] + '''-tspan"
        x="''' + str(sin(current_angle) * 112) + '''"
        y="''' + str(-cos(current_angle) * 112) + '''"
        style="text-align:center;line-height:0%;text-anchor:middle"
        dy="5.5">''' + self.axis_title[i] + '''
      </tspan>
    </text>
  '''
        svg += '  </g>'
                
        
        for serie in self.series:
            svg += '''
  <g transform="translate(128,128)" id="''' + serie.title + '''">
    <path d="M '''
            for i in range(0, axis_title_count):
                current_angle = axis_title_angle * i
                value = float(serie.values[i]) / float(self.max_value)
                svg += str(sin(current_angle) * 96.0 * value) + ',' +\
                       str(-cos(current_angle) * 96.0 * value) + ' '
            svg += '''z" id="foreground" style="fill:none;stroke:''' +\
              serie.color + '''" />
  </g>'''
        svg += '''
</svg>'''
        return svg

if __name__ == '__main__':
    rg = RadialGraph('test', ['Str', 'Con', 'Dex', 'Cog', 'Int'])
    s1 = RadialGraphSerie('s1', '#00ff00')
    s1.set_values([8, 9, 7 ,5 ,4])
    s2 = RadialGraphSerie('s2')
    s2.set_values([4, 4, 4 ,4 ,4])
    rg.add_serie(s1)
    rg.add_serie(s2)
    print(rg.get_svg())